#!/bin/bash
kubectl apply -f config.yaml

kubectl apply -f persistent-volume.yaml

kubectl apply -f pv-claim.yaml

kubectl apply -f db_deployment.yaml

kubectl apply -f postgres-service.yaml

minikube image build -t postgres-test:latest .

kubectl delete deployment postgres-app

kubectl apply -f app_deployment.yaml

kubectl apply -f app_service.yaml

kubectl apply -f app_ingress.yaml